# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.19.1
# Mod Properties
mod_version=1.0.0
maven_group=org.dx
archives_base_name=a-basic-soundboard
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.145.4+26.1.2
# Simple Voice Chat API
voicechat_api_version=2.6.13
# MP3 Decoder (JavaZoom JLayer)
jl_version=1.0.1
